# Generated by Django 5.1.5 on 2025-03-05 21:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=255)),
                ('start_date_time', models.DateTimeField()),
                ('number_of_players', models.IntegerField()),
                ('time', models.IntegerField()),
                ('invite_id', models.CharField(max_length=10)),
                ('game_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to='game.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('time_diff', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distances', to='game.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('location_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='game.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_score', models.IntegerField()),
                ('time_score', models.IntegerField()),
                ('ques_score', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='game.user')),
            ],
        ),
        migrations.CreateModel(
            name='Waypoint',
            fields=[
                ('waypoint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('waypoint_name', models.CharField(max_length=255)),
                ('lat', models.IntegerField()),
                ('lon', models.IntegerField()),
                ('height', models.IntegerField()),
                ('hint', models.TextField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('ques_dif_level', models.IntegerField()),
                ('waypoint_geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waypoints', to='game.game')),
            ],
        ),
    ]
