# Generated by Django 5.1.5 on 2025-03-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='number_of_players',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdistance',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userdistance',
            name='time_diff',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userlocation',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='location_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='ques_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='time_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='total_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='lon',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='waypoint',
            name='ques_dif_level',
            field=models.FloatField(),
        ),
    ]
